"""empty message

Revision ID: 99298fe37f8f
Revises: e12a1e37be8b
Create Date: 2019-06-08 22:13:14.361207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99298fe37f8f'
down_revision = 'e12a1e37be8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('multiply_commodities', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'multiply_commodities')
    # ### end Alembic commands ###
