"""empty message

Revision ID: d1dc4236c6f4
Revises: 99298fe37f8f
Create Date: 2019-06-09 00:35:51.673315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1dc4236c6f4'
down_revision = '99298fe37f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trolley', sa.Column('inTrolley', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trolley', 'inTrolley')
    # ### end Alembic commands ###
