"""empty message

Revision ID: e12a1e37be8b
Revises: 6bba09a74ba2
Create Date: 2019-06-08 21:41:03.608442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12a1e37be8b'
down_revision = '6bba09a74ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'name')
    # ### end Alembic commands ###
